[GENERAL]

# The simulation hash of the simulation that is analysed
simHash = b29b7b1962

# Module name of the simulation that is analysed (the analysis is tested for com4FlowPy)
modName = com4FlowPy

# column and row number (x and y  coordinate of raster) of the starting cell of the thalweg/path
# if (startRow or startCol) and relId is empty, for all thalwegData (with relating center of variable) are plotted
startRow =
startCol =
relId =

# output variable that is plotted (of whole simulation)
plotVariable = zdelta
# which center of is used
# possible:CoF (center of flux, default), CoZd (center of zdelta), CoE(center of energy)
# if empty all files are plotted
centerOfVariable = CoF

# If True, all thalwegs are represented in the field plot (upper panel)
thalwegPra = True
colorPra = 6900D1

# Avalanche size is only for the plot title
avalancheSize =

# variable that is used for statistic boxplots over all thalwegs
# possible: travelLength, velocity, impressure,
# travelLengthAveraged, velocityAveraged, impressureAveraged, zdeltaAveraged
# alphaIn, velocityMaxIn, zdeltaMaxIn  (both are the input data)
# "averaged" means that the averaged thalweg values are used (not read from raster along thalweg)
#TODO: add
statisticVariable = velocity

# if plotLogScale is True the y axis of the statistic boxplots is logarithmic
plotLogScale = False

[FLAGS]
# flags which plots should be saved:
plotStatisticBoxplot = True
plotStatisticScatterPlot = True
plotAllThalwegLocations = True
# these plots are done for each thalweg
plotThalwegLocation = False
plotThalweg2D = False
plotThalwegAltitude = False


[SIZECLASS]
# colors for the sizes
colorSize1 = 008B8B
colorSize2 = 4682B4
colorSize3 = 6495ED
colorSize4 = CD5C5C
colorSize5 = B22222

# boundaries for sizes
# for runout length [m]
travelLengthSize1Max = 50
travelLengthSize2Max = 200
travelLengthSize3Max = 1000
travelLengthSize4Max = 2000

# for impact pressure [kPa]
impressureSize1Max = 5
impressureSize2Max = 50
impressureSize3Max = 250
impressureSize4Max = 750


[ana5Utils_DFAPathGeneration_override]
# use default com1DFA config as base configuration (True)
# if False and local is available use local
defaultConfig = True

# extension method at the top
# option 0: take the highest particle in the release
# option 1: find the point that will lead to the longest runout
# option 2: find path depending on flow direction
extTopOption = 2

# the path extracted from the DFA simulation is re-sampled
# re-sampling step size is defined resampleDistance = nCellsResample x cellSize)
nCellsResample = 2
# Degree of the spline for splprep.
kResample = 1

# when extending the path at the bottom, extend path in
# the direction extracted form the last points of the path
# (all points at a distance nCellsMinExtend x cellSize < distance < nCellsMaxExtend x cellSize
# from the end)
nCellsMinExtend = 1
nCellsMaxExtend = 20
# this value needs to be chosen in accordance with nCellsResample (if nCellsMaxExtend < nCellsResample no points
# might be found for the path extension process)

# for the extrapolation at the bottom, add factBottomExt * sMax to the path (and then check if the extension
# is on the DEM, if not iterate by dichotomy until we find a point on the topography or reach a maximum
# iteration number (integer, in this case we pick the last point found inside the dem)
# or precision (nBottomExtPrecision * cellSize))
factBottomExt = 0.5
maxIterationExtBot = 10
nBottomExtPrecision = 10

