### Config File - This file contains the main settings the morris SA 

# Sidenote: (1) when running runMorrisSA.py the working directory needs to be in the ana6Optimisation folder
#           (2) avaDirectory in avaframeCfg.ini need ../ as prefix 		

# SA ... sensitivity analysis

[GENERAL]
# USER input for running and plotting a comparison of simulation result to reference polygon
# These parameters correspond to the settings in runPlotAreaRefDiffs.py
resType = ppr
thresholdValueSimulation = 1
modName = com8MoTPSA
# layer to use for analysis (e.g. L1, L2)
layer = L2

# Output Settings:
# in this folder the results will be saved, avalancheDir + this folder
resultDir = Outputs/ana6MorrisSA

[LOSS_PARAMETERS]
# The loss function evaluates the agreement between simulation results and reference data. It is defined as a weighted sum of a modified Tversky score (1 - Tversky score) and the normalized runout length difference. Areal indicators are calculated only within the avalanche impact area, which is determined by the reference polygon and a cropshape polygon.

# alpha gives penalty if simulation overshoots the reference (FP)
# beta gives penalty if simulation falls short of the reference (FN)
tverskyAlpha = 2
tverskyBeta = 1

# Loss function: (1-TverskyScore) * weightTversky + RunoutNormalised * weightRunout
weightTversky = 0.25
weightRunout = 0.75

[MORRIS SA]
# confidence level and number of levels used for SA
conf_level = 0.95
num_levels = 6
# number of best morris simulations used for statistics (topN < available model runs)
topN = 10


[MORRIS_CONVERGENCE]
# for morris convergence plot, morris needs to be run with different morris trajectories prior
# define Output folder where results of morris analyses with different trajectories (R) are saved, naming: OutputsRNumber
Outputs1 = OutputsR5
Outputs2 = OutputsR10
Outputs3 = OutputsR20
Outputs4 = OutputsR40

# get order of parameters from this output, also save result of convergence into child folders of this parent folder
referenceOutput = OutputsR10



